services:
  consul:
    image: hashicorp/consul:1.15
    container_name: consul
    volumes:
      - ./consul/consul.json:/consul/config/consul.json
      - consul_data:/consul/data
    ports:
      - "8500:8500"   # UI
      - "8600:8600/udp"
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
    restart: unless-stopped

  db1:
    build: db/
    container_name: db1
    env_file:
      - .env
    environment:
      PATRONI_NAME: db1
    volumes:
      - db1_data:/home/patroni/pgdata
    ports:
      - "5433:5432"
      - "8001:8008"
    depends_on:
      - consul
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8008/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  db2:
    build: db/
    container_name: db2
    env_file:
      - .env
    environment:
      PATRONI_NAME: db2
    volumes:
      - db2_data:/home/patroni/pgdata
    ports:
      - "5434:5432"
      - "8002:8008"
    depends_on:
      - consul
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8008/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgpool:
    image: bitnami/pgpool:latest
    container_name: pgpool
    env_file:
      - .env
    environment:
      PGPOOL_BACKEND_NODES: 0:db1:5432,1:db2:5432
      PGPOOL_SR_CHECK_USER: postgres
      PGPOOL_POSTGRES_USERNAME: postgres
      PGPOOL_ENABLE_LOAD_BALANCING: "yes"
      PGPOOL_ENABLE_HEALTH_CHECK: "yes"
      PGPOOL_HEALTH_CHECK_PERIOD: 10
      PGPOOL_HEALTH_CHECK_TIMEOUT: 5
      PGPOOL_HEALTH_CHECK_MAX_RETRIES: 3
    ports:
      - "5432:5432"
    depends_on:
      db1:
        condition: service_healthy
      db2:
        condition: service_healthy
    restart: unless-stopped

volumes:
  consul_data:
  db1_data:
  db2_data:
